<?php

namespace common\models\portfolio;

use Yii;

/**
 * This is the model class for table "portfolio_category".
 *
 * @property integer $id
 * @property string $name
 *
 * @property PortfolioItem[] $portfolioItems
 */
class Category extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'portfolio_category';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 155],
            [['sort'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'sort' => 'Сортировка',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPortfolioItems()
    {
        return $this->hasMany(PortfolioItem::className(), ['category_id' => 'id']);
    }

    public function beforeDelete()
    {
        Item::deleteAll(['category_id' => $this->id]);

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
